version: '3.8'

services:
  app:
    build:
      context: ./auth-service
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://root:roottedexample@31.207.74.78:3306/user-service
    volumes:
      - ./auth-service:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - app-network
  main:
      build:
        context: ./k8s
      ports:
        - "3001:3000"
      environment:
        DATABASE_URL: mysql://root:roottedexample@31.207.74.78:3306/main
      volumes:
        - ./k8s:/k8s
        - /k8s/node_modules
      command: npm run dev
      networks:
        - app-network
      restart: always
      healthcheck:
        test: ["CMD", "curl", "-f", "https://hackaton.testagsoft.ru/api/k8s/cluster/12/metrics?query=sum(node_memory_MemTotal_bytes%20-%20node_memory_MemAvailable_bytes)"]
        interval: 30s        
        timeout: 10s        
        retries: 3          
        start_period: 20s   

  nginx:
    image: nginx:1.24.0  
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt

    depends_on:
      - app
      - main
    networks:
      - app-network
networks:
  app-network:
    driver: bridge